title: 中国石油大学（北京）第九艺术研发社
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://cupgdc.github.io

aux_links:
  Template Repository: https://github.com/cupgdc
