title: CUP游研社Wiki
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
remote_theme: "pmarsceill/just-the-docs"

url: https://cupgdc.github.io

aux_links:
  Template Repository: https://github.com/cupgdc
